menu:
    Blog: /
    Archive: /archives/
    Telegram: https://t.me/NevadaCities
    GitHub: https://github.com/NevadaCities
    Rss: /atom.xml

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo:

# Copyright Infomation
startyear: 2021
